### ISSUE TITLE
Add an inventory to the player.java and flesh out item.java

### ISSUE THREAD

**Issue by jakesavi** [makeopensource/Classic-RPG#43]
Is your feature request related to a problem? Please describe.
-------------------------------------------
Inventory should be a list of interactable and pocketable objects for the player (ex. Armor, weapon, or item class.) 
Describe the solution you'd like
-------------------------------------------

This should be a list of Armor, Weapons, and items. (Maybe armor and weapon should extend items.)
We also require items to be fleshed out for this to be complete.

Describe alternatives you've considered
-------------------------------------------
If you come up with a better alternative to this inventory system. Please run it by me! (@jakesavi)

**Comment by pmoghe739** [comment]
Hello i am interested to contribunte on this project.
Could you explain a little as to what is expected ??
