### ISSUE TITLE
[Feature Request] Core Game Loop

### ISSUE THREAD

**Issue by russella26** [makeopensource/Classic-RPG#63]
Create an update function that can update the game state, and a loop that allows the player to move within the game.

**Comment by russella26** [comment]
@jakesavi feel free to edit the description to better reflect your implementation

**Comment by jakesavi** [comment]
Better improved default constructors for all mobiles. Now an update function for every entity needs to be executed.

**Comment by jakesavi** [comment]
> Better improved default constructors for all mobiles. Now an update function for every entity needs to be executed.  


See the TODO in the update function.
