### ISSUE TITLE
[BUG] else if should be switch

### ISSUE THREAD

**Issue by Sploder12** [makeopensource/Classic-RPG#68]
Subject of the issue
-------------------------------------------
The else if chain on line 93 of Position.java should be a switch case.

Expected behavior
-------------------------------------------
Programmer uses switch case with enum.

Actual behavior
-------------------------------------------
Programmer used else if with enum.

Steps to reproduce
-------------------------------------------
Look at line 93 of Position.java.

**Comment by Dylanz5** [comment]
I did it
