### ISSUE TITLE
Improve .dl file layout

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/Classic-RPG#91]
Is your feature request related to a problem? Please describe.
-------------------------------------------
The .dl file layout works well for small datasets, but with larger datasets with lots of text and many parameters, it begins to fall apart.

Describe the solution you'd like
-------------------------------------------
A new .dl filetype should be developed. The current parser should be moved to a new file, and expanded to include the following:

- [ ] Check .dl version number in header `example header: version: 1.5`
- [ ] Use .dl version number to redirect to a parser for that specific version
- [ ] For the v2 parser, develop the new layout, as specified below:

```
version: 2.1
---
1 | Castle
node_type: location
text-interaction: You run from the dragon.

2 | Health Potion
node_type: potion
text-interaction: You take the health potion
health: +25
xp: +100
coins: -5

3 | Dungeon
node_type: Location
text-interaction: You take the health potion
health: +0
xp: +0
coins: +100
---
1 -> 2
2 -> 3
1 \-> 3
```

**Comment by WeirdAlex03** [comment]
I imagine we'll probably be updating the file layout rather frequently this early in development. I think it would be better to have the file version in two parts, as in `0.2`. This would follow the standard `major.minor` pattern, with all pre-release changes as `0.x`. The 3-part version number, `major.minor.bugfix` is also an option, but I don't think we'll need the third class for the file type. Maybe for the parser, but not for the file itself.

**Comment by emilkovacev** [comment]
Good point! I'll revise the file format to match your suggestion

**Comment by emilkovacev** [comment]
I would also like to add parser specifications:
* v2.x will have 3 sections to the .dl file:
  * Section 1: Metadata (version number, game title, etc.)
  * Section 2: Game (node_type, node_alias, parameters)
  * Section 3: Connections (list of connected node_aliases)
* Each section is separated by three dash characters, `---`
* Empty newlines separating sections should be ignored
* Empty spaces, tabs, newlines separating data should be ignored
* Spaces between words should **not** be removed, spaces around sentences should be stripped
* Headers with values that start with either `+` or `-` should be parsed into the appropriate numbers. Positive numbers must always start with `+`
* **Comprehensive error checking for files should be employed**
